Some fixes and improvements
faniereynders/dotnet-sdk-helpers pull request #2
Opened 2017-07-15 17:25 UTC by Sekku

- Check the input to be an installed version
- Resolved issue #1

2017-07-16 19:37 UTC, faniereynders commented on dotnet-sdk.cmd
> +:swicth
Please fix typo: Swicth -> Switch

2017-07-16 19:37 UTC, faniereynders commented on dotnet-sdk.cmd
> +    if %1==%%f goto swicth
Please fix typo: Swicth -> Switch

2017-07-16 19:38 UTC, faniereynders requested changes
Kindly fix some spelling errors, thanks!

2017-07-17 19:31 UTC, andrewlock commented
Nice - though I wonder if the parent global.json check could be improved? This only checks the parent directory itself right? If you're going to warn about there being a global.json in a parent directly, you should probably walk all the way up the directory path. 

Given that you are explicitly creating a new global.json anyway, I think deleting parent ones is unnecessary, and has potentially undesirable consequences (deleting a global.json will affect other projects in sibling folders that were using it).

2017-07-17 20:44 UTC, Sekku commented
For the first point, I made a mistake assuming it would be the _first_ parent folder the one that matters and not the higher ones, so yes, it should go up all the way but considering your second point (and that's why I made deleting the global.json in the parent folder optional), if it's there, it's for a reason

Maybe switching to the latest version could be changed to:
1. Check if there's a global.json in a parent folder
2. If there's one, ask whether the user wants to switch to the latest sdk installed or to version in the global.json
2.1 If the latest installed is selected => create a global.json in the current folder with it
2.2 If the global version is selected => Do nothing / delete current global.json
3. If there isn't any file, then just delete current global.json

2017-07-18 17:49 UTC, andrewlock commented
Yup, that seems reasonable :) especially if we say what version is in the parent global.json!

2017-07-27 08:07 UTC, faniereynders commented
Great work! Thank you!

2017-07-27 08:07 UTC, merged